export const siteConfig = {
  title: "Schaide Nunes",
  description: "Welcome to my full stack Vite + React space portfolio.",
  keywords: [
    "reactjs",
    "vite",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Schaide Nunes",
    url: "https://github.com/SchaideNunes",
  },
} as const;
